version: 2.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

shallow_clone: true
clone_depth: 1

skip_tags: true

configuration:
  - Release-Far2
  - Release-Far3
  
platform:
  - Win32
  - x64

build:
  project: IntChecker2.sln
  verbosity: minimal

test: off

matrix:
  fast_finish: true

install:
  - SET PATH=%PATH%;C:\msys64\usr\bin
  - cd extra
  - m4 -P version.txt.m4 > version.txt
  - SET /p PVER=<version.txt
  - appveyor UpdateBuild -Version %PVER%.%APPVEYOR_BUILD_NUMBER%
  - DEL version.txt

after_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    xcopy bin\%configuration%-%platform%\* export\IntChecker2 /E /I /Y > nul

    IF "%configuration%" == "Release-Far3" xcopy extra\scripts\* export\IntChecker2\scripts /E /I /Y > nul

    cd export

    7z a -r -sdel -bd -- IntChecker2_%configuration:~-4%_%VC_ARCH%_%PVER%_%APPVEYOR_REPO_COMMIT:~0,7%.7z *

artifacts:
  - path: export\*.7z
